server:
  port: 8099
  
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config 
eureka:
  instance:
    non-secure-port: ${server.port:8099} 
    metadata-map:
      instanceId: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/